web-platform-tests/rfcs

- README.md
Addresses https://github.com/web-platform-tests/rfcs/issues/1#issuecomment-454103641.
> Expand on "When to use the RFC process"

- README.md
Advantages would tend to be obvious, as would Motivation as previously
required in the issue template. But thinking about the risks is useful,
and wouldn't naturally show up under summary or details.
> Reduce required RFC sections to Summary/Details/Risks

- rfcs/manifest-working-copy.md
[Rendered](https://github.com/gsnedders/rfcs/blob/manifest-working-copy/rfcs/manifest-working-copy.md)
(so GitHub picks it up: references https://github.com/web-platform-tests/wpt/issues/7206)
> Always use the working copy for the manifest

- rfcs/simplify_license.md
This RFC is an attempt to restart a stalled discussion from 2018. Since opinions on this topic may differ among the newly-formed WPT Core Team, the team may want to reach consensus before requesting approval from @wseltzer and the Patents and Standards Interest Group.
Also note that there are two subtly different pull requests implementing this change: [gh-11191](https://github.com/web-platform-tests/wpt/pull/11191) and [gh-13650](https://github.com/web-platform-tests/wpt/pull/13650). The team should decide which of these is desired.
Separately: is it appropriate to reference individuals in non-technical RFCs like this? Using GitHub handles seemed too informal (and proprietary besides), but I'm not sure if it's presumptuous to use real names. And while I think listing each person's …
> RFC 18 - Simplify License

- rfcs/remove_stub.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/foolip/remove_stub/rfcs/remove_stub.md)
> RFC: Remove support for stub-* files in the manifest

- rfcs/ahem_webfont.md
- rfcs/assert_throws.md
- rfcs/manifest-working-copy.md
- rfcs/remove_stub.md
- rfcs/single_test.md
This requirement is defined in the project README file:
> Each RFC requires a PR in this repository consisting of a single
> markdown file added to the `rfcs` directory setting out the proposed
> change. This file must have the PR number as the title and at least
> the following sections:
Update the RFCs which omit their number.
> Add RFC numbers to RFC titles

- rfcs/load_test.md
Add a test type that just ensures that a page can be loaded without error.
> Add RFC for `crash` test type

- rfcs/manifest-path-trie.md
Rendered: https://github.com/gsnedders/rfcs/blob/manifest-path-trie/rfcs/manifest-path-trie.md.
See also #20 and https://github.com/web-platform-tests/wpt/pull/16537.
> Manifest path trie RFC

- rfcs/quic.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/quic/rfcs/quic.md)
This RFC addresses https://github.com/web-platform-tests/wpt/issues/19114
cc @yutakahirano
> RFC 42: QUIC server in WPT

- rfcs/assert_precondition_rename.md
See https://github.com/web-platform-tests/wpt/issues/21971 for background information
> RFC #48: Split 'assert_precondition' into optional and non-optional variants

- rfcs/crash_test.md
* We eventually named it "crashtest".
* The class name implemented was `test-wait`.
I'm not sure whether it was an oversight or something changed later. I think we should fix the RFC (or maybe retroactively add another one, which seems a bit much) to avoid the confusion.
> Update and rename load_test.md to reflect reality

- rfcs/wptserve_py3.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/ee5eb6335c45da2357d6fc39fc8aab89ec6c6545/rfcs/wptserve_py3.md)
> RFC 49: Python 3 migration for wptserve

- rfcs/test_arrow_name.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/test_arrow_name/rfcs/test_arrow_name.md)
see also https://github.com/web-platform-tests/wpt/pull/25853
> Use arrow funcs as the default test name

- rfcs/top_level_subdomain.md
It would be simpler to write tests for features that rely on interaction between subdomains in a site
if the top-level document could be loaded from a domain other than the `web-platform.test` apex.
Addresses web-platform-tests/wpt#20932
> Consider adding a `.www` file name flag.

- rfcs/python-file-handler-local-imports.md
Implementation CL: https://github.com/web-platform-tests/wpt/pull/26328/
> RFC 68: Make local imports in Python file handlers root-relative

- rfcs/testdriver_cookie_methods.md
PR to add support for `delete_all_cookies` here: https://github.com/web-platform-tests/wpt/pull/26723
> RFC 74: Add testdriver.js support for WebDriver delete_all_cookies command

- rfcs/webtransport_h3_test_server.md
Hi web-platform-tests,
We would like to introduce a new test server for WebTransport over HTTP/3 so that we can write WPTs for WebTransport. [Rendered version](https://github.com/bashi/rfcs/blob/08cd404ee62df4dd93b11175310d44fa98187c96/rfcs/webtransport_h3_test_server.md).
cc/ @yutakahirano @ricea
> RFC 85: WebTransport over HTTP/3 test server (#85)

- rfcs/remote_channel.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/remote_channel/rfcs/remote_channel.md)
[Implementation](https://github.com/web-platform-tests/wpt/pull/29803)
> RFC 98: Remote channels for cross-browsing-group communication

- rfcs/compat_2022.md
- rfcs/interop_2022.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/compat_2022/rfcs/interop_2022.md) (easier to review than the raw Markdown)
Proposals, meeting agenda, etc., are in https://github.com/web-platform-tests/interop-2022 
This RFC is **ready for review** as of Jan 21.
> RFC 99: Interop 2022

- rfcs/proxy_for_connection_testing.md
Use an http proxy and a [PAC file](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file) to create artificial connection delays and use fresh domain names for tests.
Can help test many features that are currently untested, see for example https://github.com/whatwg/fetch/pull/1429, https://github.com/web-platform-tests/wpt/issues/27935,  and https://github.com/web-platform-tests/wpt/issues/13465
> RFC 112: Proxy for connection timing tests

- rfcs/test_scoring_change.md
This is a proposal for a larger change to the results view of wpt.fyi.
The run in the left column is aggregated using the new method, compared to the old totals displayed in the right column. This change more accurately represents the scope of test failures.
> RFC 114: Change results aggregation on wpt.fyi and visualization on Interop-20** views

- rfcs/interop_2023.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/interop_2023/rfcs/interop_2023.md)
> RFC 116: Interop 2023

- rfcs/get_signal.md
This corresponds to https://github.com/web-platform-tests/wpt/issues/34526 and https://github.com/web-platform-tests/wpt/pull/34668.
> RFC 115: Add a new test method that returns AbortSignal

- rfcs/rfc_exemption_testdriver_method.md
> RFC 127: Add RFC Exemption for testdriver.js methods similar to WebDriver endpoints

- rfcs/global-window-module.md
> RFC 133: Add support for `window-module` as JavaScript global

- rfcs/python_37.md
This ought to be possible now that Gecko CI is all using 3.7+.
> Update minimum supported Python to 3.7

- rfcs/consume_user_activation.md
See details in the proposed .md. 
tl;dr: this is a proposal to add...
* change on WPT side: https://github.com/web-platform-tests/wpt/pull/37176
```JS
/**
* Consumes the user activation
*
* Matches the behavior of the `Consume User Activation of window`
* as proposed in: https://github.com/w3c/webdriver/pull/1695
*
* Which corresponds to these steps in HTML:
* https://html.spec.whatwg.org/#consume-user-activation
*
* @param {WindowProxy} context - Browsing context in which to run the
*                                call.
* @returns {Promise<boolean>} fulfilled when user activation is consumed.
*/
consume_user_activation(context=null) {
return window.test_driver_internal.consume_user_activation(context);
},
```
> RFC 128: Consume User Activation

- rfcs/subsuites.md
This is intended to allow running multiple groups of tests, corresponding to different browser configurations in the same wptrunner process.
> Introduce 'subsuites' functionality to wptrunner

- rfcs/disable_chrome_stability.md
This RFC follows a proposal from @jgraham in a discussion on Matrix from a few days ago.
> Add RFC to disable Chromium stability checks

- rfcs/testharness_include_late_tests.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/include_late_tests/rfcs/testharness_include_late_tests.md)
> RFC 141: Change testharness to include late tests

- rfcs/address_space_overrides.md
In https://github.com/WICG/local-network-access/issues/91, we decided to rename Private Network Access to Local Network Access. The spec has already been renamed in
https://github.com/WICG/local-network-access/pull/97. The latest spec: https://wicg.github.io/local-network-access/
Chromium has also renamed private to local in
https://source.chromium.org/chromium/chromium/src/+/d5b320062c4982d2e215386e068826f8bc97c512 so the ip-address-overrides switch value needs to be updated too.
This PR makes the corresponding changes in the RFC.
cc @letitz
> Rename private to local in address space overrides

- rfcs/feature-set-metadata-file-to-web-platform-tests.md
Replacement of https://github.com/web-platform-tests/rfcs/pull/157 that uses the feedback from the last WPT [meeting](https://github.com/web-platform-tests/wpt-notes/blob/master/minutes/2023-08-01.md#rfc-157---add-feature-meta-tag-to-web-platform-tests-meta-data).
[Rendered](https://github.com/web-platform-tests/rfcs/blob/Add-feature_set-metadata-file-to-web-platform-tests/rfcs/feature-set-metadata-file-to-web-platform-tests.md)
> RFC #163: Add web_feature metadata file to web-platform-tests

- rfcs/expected_fail_message_tag_for_subtests.md
Chromium developers want to have a way to track the expected failure message, since a change in how a test fails can also be unintended and suggestive of a problem.
Made a proposal for discussion.
Bug: 42034
> RFC #165 expected-fail-message in test metadata

- rfcs/interop_charter.md
[Rendered](https://github.com/web-platform-tests/rfcs/blob/interop_charter/rfcs/interop_charter.md)
> RFC 120: Interop Team Charter

- rfcs/remove_ie_edge_legacy.md
Remove support for running WPT tests in Internet Explorer and Microsoft Edge Legacy.
> RFC 179: Remove support for Internet Explorer and Microsoft Edge Legacy

- rfcs/python_38.md
This ought to be possible now that Gecko CI is all using 3.8+.
CC @jgraham, @Ms2ger, @foolip, @gsnedders
> Update minimum supported Python to 3.8

- rfcs/crash_test_navigate.md
This helps catch a class of delayed crashes that are currently difficult to attribute to a specific test and so difficult to provide correct metadata for.
> Navigate to about:blank after loading a crashtest

- rfcs/wptfyi_enable_view_eq_test.md
Enable view=test mode in wpt.fyi
-----
[Preview](https://github.com/jcscottiii/rfcs/blob/jcscottiii/view-eq-test/rfcs/wptfyi_enable_view_eq_test.md)
> Enable view=test mode in wpt.fyi

- rfcs/docker_github_registry.md
This RFC proposes moving the container image from Docker Hub to GitHub Registry.
Issue https://github.com/web-platform-tests/wpt/issues/28903
[Preview](https://github.com/OrKoN/rfcs/blob/orkon/docker/rfcs/docker_github_registry.md)
> RFC 198: Move the container image from Docker Hub to GitHub Registry

- README.md
This captures my understanding of the meeting consensus after today's [discussion](https://github.com/web-platform-tests/wpt-notes/blob/master/minutes/2024-06-04.md#rfc-process-review). I didn't try to cover everything that was discussed, just tried to document the policy updates that would avoid a situation like #182 in the future.
We could make more updates, e.g. around what happens if the infra meeting discussion doesn't result in PR comments, what should be the relevant timeout. Another question we might want to tackle is documenting the policy for reverting (#187), but I thought I would start with what I didn't hear a clear objection on. 
I'll bring this up in the next WPT infra meeting, too.
> Clarify details around review approvals before merging

- rfcs/check_layout_wait_for_fonts.md
[Rendered](https://github.com/jonathan-j-lee/rfcs/blob/check-layout/wait-for-fonts/rfcs/check_layout_wait_for_fonts.md)
Tracking issue: https://crbug.com/375344326
> RFC 213: Wait for `document.fonts.ready` before running `checkLayout()` tests

- rfcs/testdriver_in_other_types.md
[Rendered](https://github.com/jonathan-j-lee/rfcs/blob/testdriver-in-other-types/rfcs/testdriver_in_other_types.md)
Tracking issue: web-platform-tests/wpt#13183
Prototype implementation: web-platform-tests/wpt#48486
CC: @mfreed7 @WeizhongX
> RFC 211: Support testdriver.js in other test types

- rfcs/vendoring.md
@Ms2ger suggested I file an RFC for this.
[Rendered](https://github.com/gsnedders/rfcs/blob/vendoring/rfcs/vendoring.md).
Implementation: https://github.com/web-platform-tests/wpt/pull/49752.
> RFC #218: Python vendoring
